apiVersion: v2
name: parent-chart-with-dependency
description: Parent Chart with Child Dependency
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: child-chart-dynamic-anchors
    version: 1.0.0
    repository: file://./charts/child-chart-dynamic-anchors
