{{- /*
This file was autogenerated by helmify-kustomize
DO NOT EDIT: Any changes will be overwritten
*/ -}}
{{- define "hlmfk-1-2-f4735f246e.yamls" }}
{{- if .Values.overlay }}
{{- if eq .Values.overlay "overlays/dev" }}
manifests:
  - spec: 
      apiVersion: v1
      kind: Service
      metadata:
        name: web-service
      spec:
        ports:
        - port: 80
          targetPort: 8080
        selector:
          app: web-app
  - spec: 
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-app
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: web-app
        template:
          metadata:
            labels:
              app: web-app
          spec:
            containers:
            - image: nginx:1.21
              name: web
              ports:
              - containerPort: 8080
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
{{- else}}
{{- end }}
{{- else }}
manifests: []
{{- end }}{{- end }}