{{- /*
This file was autogenerated by helmify-kustomize
DO NOT EDIT: Any changes will be overwritten
*/ -}}
{{- define "hlmfk-1-2-f4735f246e.valuesYaml" -}}
{{- $runtime_deployment_name := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "deployment_name") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_targetMemory := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "targetMemoryUtilizationPercentage") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_targetCPU := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "targetCPUUtilizationPercentage") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_maxReplicas := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "maxReplicas") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $runtime_autoscaling_minReplicas := include "hlmfk-1-2.getValue" (dict "Values" .Values "path" (list "autoscaling" "minReplicas") "default" "__HELMIFY_NOT_FOUND__") -}}
{{- $anchor_autoscaling_minReplicas_default := printf `2` -}}
{{- $anchor_autoscaling_maxReplicas_default := printf `10` -}}
{{- $anchor_autoscaling_targetCPU_default := printf `70` -}}
{{- $anchor_autoscaling_targetMemory_default := printf `80` -}}
{{- $anchor_deployment_name_default := printf `web-app` -}}
{{- $final_autoscaling_minReplicas := "" -}}
{{- if eq $runtime_autoscaling_minReplicas "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_minReplicas = $anchor_autoscaling_minReplicas_default -}}
{{- else -}}
{{- $final_autoscaling_minReplicas = $runtime_autoscaling_minReplicas -}}
{{- end -}}
{{- $final_deployment_name := "" -}}
{{- if eq $runtime_deployment_name "__HELMIFY_NOT_FOUND__" -}}
{{- $final_deployment_name = $anchor_deployment_name_default -}}
{{- else -}}
{{- $final_deployment_name = $runtime_deployment_name -}}
{{- end -}}
{{- $final_autoscaling_maxReplicas := "" -}}
{{- if eq $runtime_autoscaling_maxReplicas "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_maxReplicas = $anchor_autoscaling_maxReplicas_default -}}
{{- else -}}
{{- $final_autoscaling_maxReplicas = $runtime_autoscaling_maxReplicas -}}
{{- end -}}
{{- $final_autoscaling_targetCPU := "" -}}
{{- if eq $runtime_autoscaling_targetCPU "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_targetCPU = $anchor_autoscaling_targetCPU_default -}}
{{- else -}}
{{- $final_autoscaling_targetCPU = $runtime_autoscaling_targetCPU -}}
{{- end -}}
{{- $final_autoscaling_targetMemory := "" -}}
{{- if eq $runtime_autoscaling_targetMemory "__HELMIFY_NOT_FOUND__" -}}
{{- $final_autoscaling_targetMemory = $anchor_autoscaling_targetMemory_default -}}
{{- else -}}
{{- $final_autoscaling_targetMemory = $runtime_autoscaling_targetMemory -}}
{{- end -}}
# Test scenario for dynamic anchors with HPA autoscaling
# Creative generic solution: Use helmify-kustomize.io/enabled-by annotation
# This annotation accepts a path to a value (e.g., "autoscaling.enabled")
# and conditionally includes the manifest based on that value

autoscaling:
  enabled: true
  minReplicas: &autoscaling_minReplicas {{ $final_autoscaling_minReplicas }}

deployment_name: &deployment_name {{ $final_deployment_name }}

globals:
  patches:
    # Patch HPA with anchor values for deployment reference
    - target:
        kind: HorizontalPodAutoscaler
        name: web-app-hpa
      ops:
        - op: replace
          path: /spec/scaleTargetRef/name
          value: {{ $final_deployment_name }}
        - op: replace
          path: /spec/minReplicas
          value: {{ $final_autoscaling_minReplicas }}
        - op: replace
          path: /spec/maxReplicas
          value: {{ $final_autoscaling_maxReplicas }}
        - op: replace
          path: /spec/metrics/0/resource/target/averageUtilization
          value: {{ $final_autoscaling_targetCPU }}
        - op: replace
          path: /spec/metrics/1/resource/target/averageUtilization
          value: {{ $final_autoscaling_targetMemory }}

manifests:
  # HPA manifest with conditional rendering
  # The helmify-kustomize.io/enabled-by annotation references autoscaling.enabled
  # When autoscaling.enabled=false, this manifest will NOT be included in the chart
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: web-app-hpa
      annotations:
        helmify-kustomize.io/enabled-by: "autoscaling.enabled"
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: placeholder
      minReplicas: 1
      maxReplicas: 1
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 50
overlay: ""

{{- end -}}