export const autoGeneratedHeaderForTemplates = (version?: string) => `{{- /*
This file was autogenerated by helmify-kustomize${version ? ` v${version}` : ''}
DO NOT EDIT: Any changes will be overwritten
*/ -}}`;