import * as fs from 'fs';
import * as path from 'path';
import { autoGeneratedHeaderForTemplates } from './auto-generated-header';
/**
 * Generates the content of the chart utils file
 * @param {string} packageId - The id of the package that is used to prefix the helpers
 * @param {string} version - The version of helmify-kustomize
 * @returns {string} The content of the chart utils file
 */
export const chartUtils = (packageId: string, version?: string): string => {
  // get content of chart-utils/utils.tpl
  const utilsTplContent = fs.readFileSync(path.join(__dirname, 'chart-utils', 'utils.tpl'), 'utf8');
  // replace all occurrences of chartUtils. with packageId.
  const utilsContent = (utilsTplContent.replace(/chartUtils\./g, packageId + '.'));

  const patchUtilsTplContent = fs.readFileSync(path.join(__dirname, 'chart-utils', 'patches.tpl'), 'utf8');
  const patchUtilsContent = (patchUtilsTplContent.replace(/chartUtils\./g, packageId + '.'));
  
  return `${autoGeneratedHeaderForTemplates(version)}\n${utilsContent}\n${patchUtilsContent}`;
};


