import { analyzeYamlAnchors, AnchorInfo } from "../anchor-ref";
import { autoGeneratedHeaderForTemplates } from "./auto-generated-header";

// the following code is not longer needed as we are using a static helper
// // this will generate an helper with the name templateName that will return the value of the path
// // if the path is not found, it will return the defaultValue
// // this can be use generate a helper to get the value of a path in the values.yaml file
// // e.g references and anchors when templateName="helperName" path=["exampleReference"]. you will be able to use helper inside the chart template with $refValue := include "helperName" (dict "Values" .)
// export function generateHelmGet(namespace: string, defaultValue: string, path: (string | number)[]): string {
//   if (!path || path.length === 0) {
//     return `{{- define "${getHelperSafeGetName(namespace, path)}" -}}\n{{- "${defaultValue}" -}}\n{{- end -}}`;
//   }
  
//   let template = `{{- define "${getHelperSafeGetName(namespace, path)}" -}}\n`;
//   template += `{{- $default := "${defaultValue}" -}}\n`;
  
//   // Build the nested structure
//   let currentObject = ".Values";
//   let conditions = [];
  
//   for (let i = 0; i < path.length; i++) {
//     const segment = path[i];
//     const isLast = i === path.length - 1;
//     const varName = `$v${i}`;
    
//     if (typeof segment === 'string') {
//       // Always separate type check from hasKey check to avoid type errors
//       conditions.push({
//         type: 'map_check',
//         condition: `and ${currentObject} (kindIs "map" ${currentObject})`,
//         assignment: null,
//         finalValue: null
//       });
      
//       conditions.push({
//         type: 'key_check',
//         condition: `hasKey ${currentObject} "${segment}"`,
//         assignment: isLast ? null : `${varName} := index ${currentObject} "${segment}"`,
//         finalValue: isLast ? `index ${currentObject} "${segment}"` : null
//       });
      
//       if (!isLast) {
//         currentObject = varName;
//       }
      
//     } else if (typeof segment === 'number') {
//       // Handle array index access
//       conditions.push({
//         type: 'slice',
//         condition: `and ${currentObject} (kindIs "slice" ${currentObject})`,
//         assignment: null,
//         finalValue: null
//       });
      
//       conditions.push({
//         type: 'length',
//         condition: `gt (len ${currentObject}) ${segment}`,
//         assignment: isLast ? null : `${varName} := index ${currentObject} ${segment}`,
//         finalValue: isLast ? `index ${currentObject} ${segment}` : null
//       });
      
//       if (!isLast) {
//         currentObject = varName;
//       }
//     }
//   }
  
//   // Generate the nested if structure
//   let indent = "";
//   for (let i = 0; i < conditions.length; i++) {
//     const cond = conditions[i];
//     template += `${indent}{{- if ${cond.condition} -}}\n`;
//     indent += "  ";
    
//     if (cond.assignment) {
//       template += `${indent}{{- ${cond.assignment} -}}\n`;
//     }
    
//     if (cond.finalValue) {
//       // This is the innermost condition with the final value
//       template += `${indent}{{- ${cond.finalValue} -}}\n`;
//     }
//   }
  
//   // Close all conditions with else blocks
//   for (let i = conditions.length - 1; i >= 0; i--) {
//     indent = "  ".repeat(i);
//     template += `${indent}{{- else -}}\n`;
//     template += `${indent}  {{- $default -}}\n`;
//     template += `${indent}{{- end -}}\n`;
//   }
  
//   template += `{{- end -}}`;
  
//   return template;
// }

// export function getHelperGetAnchorFinalValueName(namespace: string,anchorName: string): string {
//   return `${namespace}.getAnchorFinalValue.${anchorName}`;
// }

// export function generateHelmGetAnchorFinalValue(namespace: string,anchorName: string , anchorPath: (string | number)[] , defaultValue: string): string {
//     const safeGetName = getHelperSafeGetName(namespace, anchorPath);
//   return `{{- define "${getHelperGetAnchorFinalValueName(namespace, anchorName)}" -}}
// {{- $defaultValueString := \`${defaultValue}\` -}}
// {{- $default := fromYaml $defaultValueString -}}
// {{- $anchorValue := include "${safeGetName}" (dict "Values" .) -}}
// {{- if $anchorValue }}
//   {{- $anchorValue }}
// {{- else }}
//   {{- $default }}
// {{- end }}
// {{- end }}`;
// }

/*

The function takes a yamlValuesString identify the anchors and generate a template that will return the values.yaml file with the anchors replaced by the values.
it is doing so by "cutting out" the anchors and replacing with call to final value helper.
note: an anchor can have in it's default value a reference to another anchor, this function will handle this case.

exmaple yaml with anchors:
```
app: &app
  replicas: 3
  port: 8080
  image: &app_image
    image: my-app
    tag: 1.0.0
testApp:
  app: *app
``` 

output:
{{- define "chartUitls.valuesYaml" -}}
{{ $runtime_app_image := include "chartUitls.getAnchorSafeGet.app_image" (dict "Values" .) }}
{{ $runtime_app := include "chartUitls.getAnchorSafeGet.app" (dict "Values" .) }}
{{ $anchor_app_image_default := printf `
image: my-app
tag: 1.0.0
` }}
{{ $final_app_image := (include "chartUitls.pickFirstNonEmpty" (list $runtime_app_image $anchor_app_image_default))}}
{{ $anchor_app_default := printf `
replicas: 3
port: 8080
image: %v
` ($final_app_image | toYaml | indent 2)
}}
{{- $final_app := (include "chartUitls.pickFirstNonEmpty" (list $runtime_app $anchor_app_default))}}
{{ $result := printf `
app: %v
` ($final_app | toYaml | indent 2)
}}
{{ $result | toYaml }}
{{- end }}


Notice that references (*app ..) are not replaced! as once the yaml string is parsed this will managed by the yaml parser.



*/
export function generateValuesYamlTemplate(namespace: string , chartUtilsNamespace: string, yamlValuesString: string): string {
    const anchors = analyzeYamlAnchors(yamlValuesString);
    
    if (anchors.length === 0) {
      // No anchors found, return simple template
      return `${autoGeneratedHeaderForTemplates}
{{- define "${namespace}.valuesYaml" -}}
${yamlValuesString}
{{- end -}}`;
    }
    
    // Sort anchors by dependency order (anchors that reference other anchors come after their dependencies)
    const sortedAnchors = topologicalSortAnchors(anchors);
    
    // Generate template lines
    const templateLines: string[] = [];
    templateLines.push(`${autoGeneratedHeaderForTemplates}
{{- define "${namespace}.valuesYaml" -}}`);
    
    // Generate runtime variable declarations for each anchor using chart utils getValue helper
    sortedAnchors.slice().reverse().forEach(anchor => {
      const varName = `$runtime_${anchor.name}`;
      const pathList = anchor.path.map(p => `"${p}"`).join(' ');
      // Use a special marker for "not found" instead of the actual default
      const notFoundMarker = '__HELMIFY_NOT_FOUND__';
      templateLines.push(`{{- ${varName} := include "${chartUtilsNamespace}.getValue" (dict "Values" .Values "path" (list ${pathList}) "default" "${notFoundMarker}") -}}`);
    });
    
    // Generate default value declarations for each anchor
    sortedAnchors.forEach(anchor => {
      const defaultVarName = `$anchor_${anchor.name}_default`;

      // Special handling for anchors with merge keys
      if (anchor.hasMergeKey && anchor.mergedAnchors && anchor.mergedAnchors.length > 0) {
        // Build the merged value by combining the merged anchor with additional keys
        const mergedAnchorName = anchor.mergedAnchors[0]; // Currently handling single merge
        const mergedRuntimeVar = `$runtime_${mergedAnchorName}`;
        const mergedDefaultVar = `$anchor_${mergedAnchorName}_default`;

        // Extract the additional keys (not the merge key)
        const additionalKeys: {[key: string]: any} = {};
        if (typeof anchor.value === 'object' && anchor.value !== null) {
          for (const [key, value] of Object.entries(anchor.value)) {
            if (key !== '<<') {
              additionalKeys[key] = value;
            }
          }
        }

        // Generate the merged value template
        if (Object.keys(additionalKeys).length > 0) {
          const additionalYaml = formatYamlValue(additionalKeys);
          // Use Helm's merge function to combine the anchors
          templateLines.push(`{{- ${defaultVarName} := "" -}}`);
          templateLines.push(`{{- if eq ${mergedRuntimeVar} "__HELMIFY_NOT_FOUND__" -}}`);
          templateLines.push(`{{- ${defaultVarName} = merge (dict ${Object.entries(additionalKeys).map(([k, v]) => `"${k}" ${JSON.stringify(v)}`).join(' ')}) (${mergedDefaultVar} | fromYaml) | toYaml -}}`);
          templateLines.push(`{{- else -}}`);
          templateLines.push(`{{- ${defaultVarName} = merge (dict ${Object.entries(additionalKeys).map(([k, v]) => `"${k}" ${JSON.stringify(v)}`).join(' ')}) (${mergedRuntimeVar} | fromYaml) | toYaml -}}`);
          templateLines.push(`{{- end -}}`);
        } else {
          // Just use the merged anchor value directly
          templateLines.push(`{{- ${defaultVarName} := include "${chartUtilsNamespace}.pickFirstNonEmpty" (list ${mergedRuntimeVar} ${mergedDefaultVar}) -}}`);
        }
      } else {
        // Regular anchor handling (no merge key)
        const defaultValue = formatYamlValue(anchor.value);

        // Check if this anchor's value references other anchors
        const anchorReferences = findAnchorReferences(anchor.value, sortedAnchors);

        if (anchorReferences.length > 0) {
          // Build printf statement with placeholders for referenced anchors
          const printfParts: string[] = [];
          let formattedValue = defaultValue;

          anchorReferences.forEach(refAnchor => {
            const refPattern = new RegExp(`\\*${refAnchor.name}`, 'g');
            formattedValue = formattedValue.replace(refPattern, '%s');
            const otherRuntimeVar = `$runtime_${refAnchor.name}`;
            const otherDefaultVar = `$anchor_${refAnchor.name}_default`;
            printfParts.push(`(include "${chartUtilsNamespace}.pickFirstNonEmpty" (list ${otherRuntimeVar} ${otherDefaultVar}) | indent 2)`);
          });

          templateLines.push(`{{- ${defaultVarName} := printf \`${escapeBackticks(formattedValue)}\` ${printfParts.join(' ')} -}}`);
        } else {
          templateLines.push(`{{- ${defaultVarName} := printf \`${escapeBackticks(defaultValue)}\` -}}`);
        }
      }
    });
    
    // Build the result template by replacing both anchor definitions AND references
    // Anchor definitions (&anchor_name) and references (*anchor_name) both need to be templated
    let resultTemplate = yamlValuesString;
    const replacements: Array<{anchor: string, runtime: string, default: string}> = [];
    
    
    // Process anchor definitions (&anchor_name) 
    // For each anchor, replace the entire definition with a single placeholder
    sortedAnchors.forEach(anchor => {
      const escapedName = anchor.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      
      // Use a comprehensive approach to replace entire anchor definitions
      // This pattern matches the anchor definition line and all subsequent indented lines
      const anchorPattern = new RegExp(
        `^(\\s*\\S+:\\s*&\\s*${escapedName}\\b)(?:\\s+[^\\n]*)?(\\n(  .*))*`,
        'gm'
      );
      
      const matches = [...resultTemplate.matchAll(anchorPattern)];
      
      if (matches.length > 0) {
        // Replace from last match to first to preserve indices
        matches.reverse().forEach(match => {
          const fullMatch = match[0];
          const keyAndAnchor = match[1];
          const replacement = keyAndAnchor + ' %s';  // Use %s for string formatting
          
          const startIndex = match.index!;
          const endIndex = startIndex + fullMatch.length;
          
          resultTemplate = resultTemplate.substring(0, startIndex) + 
                          replacement + 
                          resultTemplate.substring(endIndex);
        });
        
        const runtimeVar = `$runtime_${anchor.name}`;
        const defaultVar = `$anchor_${anchor.name}_default`;
        replacements.push({
          anchor: anchor.name,
          runtime: runtimeVar,
          default: defaultVar
        });
      }
    });
    
    // Now collect all positions where we'll need to place placeholders
    // First, collect all anchor references positions before replacing
    const allReplacements: Array<{pos: number, anchorName: string, isDefinition: boolean}> = [];
    
    // Collect anchor definition positions (already have %s placeholders)
    sortedAnchors.forEach(anchor => {
      const defPattern = new RegExp(`&${anchor.name}\\s+%s`, 'g');
      let match;
      while ((match = defPattern.exec(resultTemplate)) !== null) {
        allReplacements.push({
          pos: match.index + match[0].indexOf('%s'),
          anchorName: anchor.name,
          isDefinition: true
        });
      }
    });
    
    // Collect anchor reference positions
    sortedAnchors.forEach(anchor => {
      const refPattern = new RegExp(`\\*${anchor.name}\\b`, 'g');
      let match;
      while ((match = refPattern.exec(resultTemplate)) !== null) {
        allReplacements.push({
          pos: match.index,
          anchorName: anchor.name,
          isDefinition: false
        });
      }
    });
    
    // Sort by position to get the correct order
    allReplacements.sort((a, b) => a.pos - b.pos);
    
    // Now replace anchor references with %s
    sortedAnchors.forEach(anchor => {
      const escapedName = anchor.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const referencePattern = new RegExp(`\\*${escapedName}\\b`, 'g');
      resultTemplate = resultTemplate.replace(referencePattern, '%s');
    });

    // Add all anchors to replacements list for variable generation
    sortedAnchors.forEach(anchor => {
      const runtimeVar = `$runtime_${anchor.name}`;
      const defaultVar = `$anchor_${anchor.name}_default`;
      const existing = replacements.find(r => r.anchor === anchor.name);
      if (!existing) {
        replacements.push({
          anchor: anchor.name,
          runtime: runtimeVar,
          default: defaultVar
        });
      }
    });
    
    // Build final value variables for each replacement
    replacements.forEach(replacement => {
      const finalVarName = `$final_${replacement.anchor}`;
      // Check if runtime value is the not found marker, if so use default
      // Variables must be declared at the same scope level in Helm templates
      templateLines.push(`{{- ${finalVarName} := "" -}}`);
      templateLines.push(`{{- if eq ${replacement.runtime} "__HELMIFY_NOT_FOUND__" -}}`);
      templateLines.push(`{{- ${finalVarName} = ${replacement.default} -}}`);
      templateLines.push(`{{- else -}}`);
      // Keep values as-is
      templateLines.push(`{{- ${finalVarName} = ${replacement.runtime} -}}`);
      templateLines.push(`{{- end -}}`);
    });
    
    
    // Instead of using printf, build the result by direct substitution
    // Split the template by placeholders and rebuild with actual values
    let resultParts: string[] = [];
    let currentPos = 0;
    
    // Find all %s placeholders and replace them with template variables
    const placeholderRegex = /%s/g;
    let match;
    
    // Use the allReplacements array which has the correct mapping
    let replacementIndex = 0;
    
    while ((match = placeholderRegex.exec(resultTemplate)) !== null) {
      // Add the text before the placeholder
      resultParts.push(resultTemplate.substring(currentPos, match.index));
      
      // Get the anchor name and type from our pre-computed mapping
      let anchorName = '';
      let isDefinition = false;
      if (replacementIndex < allReplacements.length) {
        anchorName = allReplacements[replacementIndex].anchorName;
        isDefinition = allReplacements[replacementIndex].isDefinition;
        replacementIndex++;
      }
      
      // Add the template variable for this placeholder
      if (anchorName) {
        const anchor = sortedAnchors.find(a => a.name === anchorName);
        
        if (anchor && typeof anchor.value === 'object' && anchor.value !== null) {
          // For complex values, we need special handling
          // Check if this is in a patch context (not a definition)
          if (!isDefinition) {
            // This is a patch value - calculate indentation at build time
            // Build the text up to this placeholder to analyze structure
            const reconstructedText = resultParts.join('') + resultTemplate.substring(currentPos, match.index);
            const lines = reconstructedText.split('\n');
            
            // Find the "value:" line we're completing
            const lastLine = lines[lines.length - 1];
            const valueLineIndent = lastLine.match(/^(\s*)value:/)?.[1]?.length || 0;
            
            // Content under "value:" should be indented by the standard YAML increment
            // Detect the indentation increment used in this file
            let indentIncrement = 2; // default to 2 spaces
            
            // Look for any list item to determine indent style
            const listItemMatch = reconstructedText.match(/\n(\s+)- \w/);
            if (listItemMatch) {
              // Find the parent line's indentation
              const beforeList = reconstructedText.substring(0, reconstructedText.indexOf(listItemMatch[0]));
              const parentLines = beforeList.split('\n');
              for (let i = parentLines.length - 1; i >= 0; i--) {
                if (parentLines[i].trim() && !parentLines[i].trim().startsWith('-')) {
                  const parentIndent = parentLines[i].match(/^(\s*)/)?.[1]?.length || 0;
                  indentIncrement = listItemMatch[1].length - parentIndent;
                  break;
                }
              }
            }
            
            // Calculate the content indentation
            const contentIndent = valueLineIndent + indentIncrement;
            
            // Use the calculated indent
            resultParts.push(`{{ $final_${anchorName} | fromYaml | toYaml | nindent ${contentIndent} }}`);
          } else {
            // This is an anchor definition - for complex objects, format on next lines
            // We'll add a newline and indent the complex value
            resultParts.push(`\n{{ $final_${anchorName} | indent 2 }}`);
          }
        } else {
          // Scalar value
          resultParts.push(`{{ $final_${anchorName} }}`);
        }
      }
      
      currentPos = match.index + match[0].length;
    }
    
    // Add any remaining text after the last placeholder
    resultParts.push(resultTemplate.substring(currentPos));
    
    // Join all parts to create the final template
    const finalTemplate = resultParts.join('');
    
    templateLines.push(finalTemplate);
    templateLines.push(`{{- end -}}`);
    
    return templateLines.join('\n');
}

// Helper function to escape backticks in template strings
function escapeBackticks(str: string): string {
  return str.replace(/`/g, '\\`');
}

// Helper function to find anchor references in a value
function findAnchorReferences(value: any, anchors: AnchorInfo[]): AnchorInfo[] {
  const valueStr = JSON.stringify(value);
  const references: AnchorInfo[] = [];
  
  anchors.forEach(anchor => {
    if (valueStr.includes(`*${anchor.name}`)) {
      references.push(anchor);
    }
  });
  
  return references;
}

// Helper function to perform topological sort on anchors based on their dependencies
function topologicalSortAnchors(anchors: AnchorInfo[]): AnchorInfo[] {
  const anchorMap = new Map(anchors.map(a => [a.name, a]));
  const visited = new Set<string>();
  const sorted: AnchorInfo[] = [];
  
  // Find dependencies for each anchor (which other anchors it references)
  const dependencies = new Map<string, Set<string>>();
  
  anchors.forEach(anchor => {
    const deps = new Set<string>();
    const valueStr = JSON.stringify(anchor.value);

    // Check if this anchor's value references other anchors
    anchors.forEach(otherAnchor => {
      if (anchor.name !== otherAnchor.name && valueStr.includes(`*${otherAnchor.name}`)) {
        deps.add(otherAnchor.name);
      }
    });

    // Also add dependencies for merge keys
    if (anchor.hasMergeKey && anchor.mergedAnchors) {
      anchor.mergedAnchors.forEach(mergedAnchor => {
        deps.add(mergedAnchor);
      });
    }

    dependencies.set(anchor.name, deps);
  });
  
  // Topological sort using DFS
  function visit(name: string) {
    if (visited.has(name)) return;
    visited.add(name);
    
    const deps = dependencies.get(name) || new Set();
    deps.forEach(dep => visit(dep));
    
    const anchor = anchorMap.get(name);
    if (anchor) sorted.push(anchor);
  }
  
  anchors.forEach(anchor => visit(anchor.name));
  
  return sorted;
}



// Helper function to format YAML value as a string
function formatYamlValue(value: any, indent: number = 0): string {
  const indentStr = '  '.repeat(indent);
  
  if (value === null || value === undefined) {
    return 'null';
  }
  
  if (typeof value === 'string') {
    return value;
  }
  
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  
  if (Array.isArray(value)) {
    return value.map((item, index) => {
      const itemStr = formatYamlValue(item, indent + 1);
      const prefix = index === 0 ? '' : '\n' + indentStr;
      
      if (typeof item === 'object' && item !== null) {
        const itemLines = itemStr.split('\n');
        return `${prefix}- ${itemLines[0]}${itemLines.slice(1).map(line => '\n' + indentStr + '  ' + line).join('')}`;
      }
      
      return `${prefix}- ${itemStr}`;
    }).join('');
  }
  
  if (typeof value === 'object' && value !== null) {
    return Object.entries(value).map(([key, val], index) => {
      const prefix = index === 0 ? '' : '\n' + indentStr;
      
      if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
        const childStr = formatYamlValue(val, indent + 1);
        return `${prefix}${key}:\n${indentStr}  ${childStr.split('\n').join('\n' + indentStr + '  ')}`;
      }
      
      const valueStr = formatYamlValue(val, indent + 1);
      return `${prefix}${key}: ${valueStr}`;
    }).join('');
  }
  
  return '';
}

