import { trimIndent } from '../lang';
import { autoGeneratedHeaderForTemplates } from './auto-generated-header';
import { singleOverlay } from './single-overlay-content';

/**
 * Interface representing the result of processing a Kustomize overlay
 * @interface OverlayResult 
 * @property {string} overlay - The path to the overlay directory relative to the base
 * @property {string} content - The raw YAML content generated from building the overlay
 */
interface OverlayResult {
  overlay: string;
  content: string;
}
/**
 * Generates the content of the overlays.yaml file
 * @param {string} chartPrefix - The prefix of the chart that prefixes the helper name
 * @param {OverlayResult[]} overlayResults - The results of the overlays
 * @param {string} version - The version of helmify-kustomize
 * @returns {string} The content of the overlays.yaml file
 */
export const overlaysResults = (chartPrefix: string, overlayResults: OverlayResult[], version?: string): string => {
  return trimIndent(`${autoGeneratedHeaderForTemplates(version)}
    |{{- define "${chartPrefix}.yamls" }}
        |{{- if .Values.overlay }}
        |${overlayResults
          .map(({ overlay, content }) => singleOverlay(overlay, content))
          .join('\n')}
        |{{- else }}
        |manifests: []
        |{{- end }}{{- end }}`);
};