{{- /*
This file was autogenerated by helmify-kustomize
DO NOT EDIT: Any changes will be overwritten
*/ -}}
{{- define "hlmfk-1-2-2044ba82b3.yamls" }}
{{- if .Values.overlay }}
{{- if eq .Values.overlay "overlays/dev" }}
manifests:
  - spec: 
      apiVersion: v1
      kind: Service
      metadata:
        name: child-app-service
      spec:
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          app: child-app
        type: ClusterIP
  - spec: 
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: child-app
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: child-app
        template:
          metadata:
            labels:
              app: child-app
          spec:
            containers:
            - image: child-app:latest
              name: app
              ports:
              - containerPort: 8080
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
{{- else}}
{{- end }}
{{- else }}
manifests: []
{{- end }}{{- end }}