{{- /*
This file was autogenerated by helmify-kustomize
DO NOT EDIT: Any changes will be overwritten
*/ -}}
{{- define "hlmfk-1-2-2044ba82b3.valuesYaml" -}}
# Parent chart values
# Override child chart dynamic anchor values
child-chart-dynamic-anchors:
  overlay: "overlays/dev" # Select the overlay to use
  replicas: 5 # Override the anchor value from child (was 2)
  resourceLimits:
    memory: "2Gi" # Override memory from child (was 1Gi)
    cpu: "2000m" # Override cpu from child (was 1000m)
  serviceType: NodePort # Override service type from child (was LoadBalancer)
overlay: ""

{{- end -}}